config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello' 

  get 'greeter/goodbye'

  root 'courses#index'

end

app/models/concerns/coursera.rb
require 'pp'

class Coursera 
    include HTTParty

    base_uri 'https://api.coursera.org/api/catalog.v1/courses'
    default_params fields: "smallIcon,shortDescription", q:"search"
    format :json

    def self.for term 
        get("", query: { query: term})["elements"]
    end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index    
    @search_term = params[:looking_for]
    if Coursera.for(@search_term)==nil 
     @courses= Coursera.for("jhu")
    else @courses= Coursera.for(@search_term)
    end

    end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names=["alex","dog","cat"]
    @name = random_names.sample
    @time = Time.now 
    @time_displayed ||=0
    @time_displayed+=1 
  end
  def goodbye
    random_names=["alex","dog","cat"]
    @name = random_names.sample
    @time = Time.now 
    @time_displayed ||=0
    @time_displayed+=1 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time(time)
        time.strftime("%I:%M%p")
    end
    
end

app/views/courses/index.html.erb
<h1>Searching for  - <%= @search_term %> </h1> 

<table border="1">
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>description</th>
    </tr>
<% @courses.each do |course| %>
    <tr>
        <tr class=<%= cycle('even','odd') %>>
            <td><%= image_tag(course["smallIcon"])%></td>
            <td><%= course["name"] %></td>
            <td><%= course["shortDescription"] %></td>
    </tr>
<% end %>
</table>

app/views/greeter/goodbye.html.erb
<h1>gg, <%= @name %></h1>
<p>the time is now <%= formatted_time(@time) %></p>
<p>this page has been displayed <%= @time_displayed %> times </p>
<p><%=link_to "google", "http://www.google.com" %></p>
<p><%=link_to "Goodbye",greeter_goodbye_path%> </p>

app/views/greeter/hello.html.erb
<h1>hello, <%= @name %></h1>
<p>the time is now <%= formatted_time(@time) %></p>
<p>this page has been displayed <%= @time_displayed %> times </p>
<p><%=link_to "google", "http://www.google.com" %></p>
<p><%=link_to "Goodbye",greeter_goodbye_path%> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>